apiVersion: apps/v1
kind: Deployment
metadata:
 name: supersimple-spring-web-metadata-name
 labels:
  app: supersimple-spring-web-labels-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: supersimple-spring-web-labels-app
 template:
  metadata:
   labels:
    app: supersimple-spring-web-labels-app
  spec:
   containers:
    - name: supersimple-spring-web
      image: ridlwan/supersimple-spring-web:1.0
      ports:
       - containerPort: 9090